require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ReportStructureElementsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ReportStructureElement. As you add validations to ReportStructureElement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReportStructureElementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all report_structure_elements as @report_structure_elements" do
      report_structure_element = ReportStructureElement.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:report_structure_elements)).to eq([report_structure_element])
    end
  end

  describe "GET show" do
    it "assigns the requested report_structure_element as @report_structure_element" do
      report_structure_element = ReportStructureElement.create! valid_attributes
      get :show, {:id => report_structure_element.to_param}, valid_session
      expect(assigns(:report_structure_element)).to eq(report_structure_element)
    end
  end

  describe "GET new" do
    it "assigns a new report_structure_element as @report_structure_element" do
      get :new, {}, valid_session
      expect(assigns(:report_structure_element)).to be_a_new(ReportStructureElement)
    end
  end

  describe "GET edit" do
    it "assigns the requested report_structure_element as @report_structure_element" do
      report_structure_element = ReportStructureElement.create! valid_attributes
      get :edit, {:id => report_structure_element.to_param}, valid_session
      expect(assigns(:report_structure_element)).to eq(report_structure_element)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReportStructureElement" do
        expect {
          post :create, {:report_structure_element => valid_attributes}, valid_session
        }.to change(ReportStructureElement, :count).by(1)
      end

      it "assigns a newly created report_structure_element as @report_structure_element" do
        post :create, {:report_structure_element => valid_attributes}, valid_session
        expect(assigns(:report_structure_element)).to be_a(ReportStructureElement)
        expect(assigns(:report_structure_element)).to be_persisted
      end

      it "redirects to the created report_structure_element" do
        post :create, {:report_structure_element => valid_attributes}, valid_session
        expect(response).to redirect_to(ReportStructureElement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved report_structure_element as @report_structure_element" do
        post :create, {:report_structure_element => invalid_attributes}, valid_session
        expect(assigns(:report_structure_element)).to be_a_new(ReportStructureElement)
      end

      it "re-renders the 'new' template" do
        post :create, {:report_structure_element => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested report_structure_element" do
        report_structure_element = ReportStructureElement.create! valid_attributes
        put :update, {:id => report_structure_element.to_param, :report_structure_element => new_attributes}, valid_session
        report_structure_element.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested report_structure_element as @report_structure_element" do
        report_structure_element = ReportStructureElement.create! valid_attributes
        put :update, {:id => report_structure_element.to_param, :report_structure_element => valid_attributes}, valid_session
        expect(assigns(:report_structure_element)).to eq(report_structure_element)
      end

      it "redirects to the report_structure_element" do
        report_structure_element = ReportStructureElement.create! valid_attributes
        put :update, {:id => report_structure_element.to_param, :report_structure_element => valid_attributes}, valid_session
        expect(response).to redirect_to(report_structure_element)
      end
    end

    describe "with invalid params" do
      it "assigns the report_structure_element as @report_structure_element" do
        report_structure_element = ReportStructureElement.create! valid_attributes
        put :update, {:id => report_structure_element.to_param, :report_structure_element => invalid_attributes}, valid_session
        expect(assigns(:report_structure_element)).to eq(report_structure_element)
      end

      it "re-renders the 'edit' template" do
        report_structure_element = ReportStructureElement.create! valid_attributes
        put :update, {:id => report_structure_element.to_param, :report_structure_element => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested report_structure_element" do
      report_structure_element = ReportStructureElement.create! valid_attributes
      expect {
        delete :destroy, {:id => report_structure_element.to_param}, valid_session
      }.to change(ReportStructureElement, :count).by(-1)
    end

    it "redirects to the report_structure_elements list" do
      report_structure_element = ReportStructureElement.create! valid_attributes
      delete :destroy, {:id => report_structure_element.to_param}, valid_session
      expect(response).to redirect_to(report_structure_elements_url)
    end
  end

end
